# Generated by Django 4.1.2 on 2022-10-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seller", "0001_initial"),
    ]

    operations = [
        migrations.AlterIndexTogether(name="cakeproducts", index_together=set(),),
        migrations.RemoveField(model_name="cakecategory", name="slug",),
        migrations.AlterField(
            model_name="cakeproducts",
            name="discountoffers",
            field=models.BooleanField(default=False, verbose_name="any discounts"),
        ),
        migrations.RemoveField(model_name="cakeproducts", name="slug",),
    ]
