# Generated by Django 3.2.15 on 2023-01-06 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seller', '0002_cakeproducts_seller'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cakeproducts',
            name='seller',
            field=models.ForeignKey(default='1', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_Owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
